#!/usr/bin/env python3
"""Generates source/game_sa/Scripts/CommandParamInfo.inc: for every script command, how many parameters it reads and
stores, and whether it is a condition. From sa.json (the Sanny Builder library). That is what it takes to step over a
command that has no handler, without derailing the script that uses it."""
import json, os
D = os.path.dirname(os.path.abspath(__file__))
cmds = {int(c["id"], 16): c for c in json.load(open(D + "/sa.json"))["extensions"][0]["commands"]}
n = max(cmds) + 1
out = [
    "// Generated by tools/script-commands/gen_param_info.py, don't edit.",
    "// { number of parameters read, number of values stored, is a condition (sets the compare flag), has a variable number of parameters }",
    "// Indexed by the command's id. From the command definitions of the Sanny Builder library (https://github.com/sannybuilder/library).",
]
for i in range(n):
    c = cmds.get(i)
    if c is None:
        out.append("{ 0, 0, false, false }, // 0x%04X (unknown)" % i)
        continue
    ins, outs = c.get("input", []), c.get("output", [])
    var = any(p.get("type") == "arguments" for p in ins)
    out.append("{ %2d, %d, %-5s, %-5s }, // 0x%04X %s" % (len(ins) - (1 if var else 0), len(outs), str(bool(c.get("attrs", {}).get("is_condition"))).lower(), str(var).lower(), i, c["name"]))
open(os.path.normpath(D + "/../../source/game_sa/Scripts/CommandParamInfo.inc"), "w", newline="\r\n").write("\n".join(out) + "\n")
print(n, "commands")
