#!/usr/bin/env python3
"""Generates launcher/StartupData.inc: what the start-up code of the original executable does to its data.

The original has 1667 initializers of global variables that run before its `WinMain` (constructors of global objects,
and initial values that take computing). A standalone game doesn't run them, so their effect has to come from somewhere:
this is it, as data. It is the difference between the data sections in the executable's file, and in memory right
before `WinMain`.

usage: generate.py <original exe> <capture 1> <capture 2>
The captures are made by the inverted loader, see `GTA_REVERSED_DUMP_STARTUP_DATA` in launcher/LoaderDll.cpp. Two of them,
from two runs: what differs between them depends on the run (addresses of allocations, handles, the stack cookie), and is left out.

Also left out: everything outside of `.data` (the import table), and the end of `.data`, where the C runtime of the original
and the Direct3D driver of its RenderWare keep their state. Neither exists in a standalone game.
"""
import os, struct, sys
if len(sys.argv) != 4:
    sys.exit(__doc__)
exe = open(sys.argv[1], "rb").read()
pe = struct.unpack_from("<I", exe, 0x3C)[0]
nsec = struct.unpack_from("<H", exe, pe + 6)[0]
opt = struct.unpack_from("<H", exe, pe + 20)[0]
base = struct.unpack_from("<I", exe, pe + 24 + 28)[0]
secs = []
for i in range(nsec):
    o = pe + 24 + opt + i * 40
    name = exe[o:o + 8].rstrip(b"\0").decode()
    vsz, va, rsz, raw = struct.unpack_from("<IIII", exe, o + 8)
    secs.append((name, base + va, vsz, rsz, raw))

def load(path):
    b = open(path, "rb").read()
    begin, end = struct.unpack_from("<II", b, 0)
    return begin, end, b[8:]

B, E, a = load(sys.argv[2])
B2, E2, b = load(sys.argv[3])
assert (B, E) == (B2, E2) and len(a) == len(b) == E - B
file_data = bytearray(E - B)
for name, va, vsz, rsz, raw in secs:
    if B <= va < E:
        k = min(rsz, vsz) if vsz else rsz
        file_data[va - B:va - B + k] = exe[raw:raw + k]

data = next(s for s in secs if s[0] == ".data")
BEGIN = data[1]
END = 0xC9A000  # From here on: the C runtime's, and RenderWare's Direct3D 9 driver's
# The C runtime also has a few things at the start of `.data`
EXCLUDE = [(0x8E30F0, 0x8E3108)]

keep = bytearray(E - B)  # 1 = this byte is to be replayed
for i in range(BEGIN - B, END - B):
    keep[i] = a[i] != file_data[i]
for i in range(0, E - B - 3, 4):  # run-dependent: the whole dword
    if a[i:i + 4] != b[i:i + 4]:
        keep[i:i + 4] = b"\0\0\0\0"
for lo, hi in EXCLUDE:
    keep[lo - B:hi - B] = bytes(hi - lo)

# runs, joining ones that are close (the bytes between are what the file has anyway)
runs, i, n = [], BEGIN - B, END - B
while i < n:
    if not keep[i]:
        i += 1
        continue
    j = i + 1
    last = i
    while j < n and j - last <= 12:
        if keep[j]:
            # don't join across something that must not be written
            if any(a[k:k + 1] != b[k:k + 1] for k in range(last + 1, j)):
                break
            last = j
        j += 1
    runs.append((B + i, last + 1 - i))
    i = last + 1
runs = [r for r in runs if not any(lo < r[0] + r[1] and r[0] < hi for lo, hi in EXCLUDE)] + []
blob = b"".join(a[addr - B:addr - B + size] for addr, size in runs)
out = [
    "// Generated by tools/startup-data/generate.py, don't edit.",
    "// What the start-up code of the original executable does to its data before `WinMain`: %d runs, %d bytes." % (len(runs), len(blob)),
    "static constexpr StartupDataRun STARTUP_DATA_RUNS[]{ // { address, size }, their bytes follow each other in `STARTUP_DATA`",
]
line = []
for addr, size in runs:
    line.append("{0x%X,%d}," % (addr, size))
    if len(line) == 8:
        out.append(" ".join(line)); line = []
if line:
    out.append(" ".join(line))
out += ["};", "static constexpr unsigned char STARTUP_DATA[]{"]
for k in range(0, len(blob), 32):
    out.append(",".join(str(x) for x in blob[k:k + 32]) + ",")
out.append("};")
dst = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "launcher", "StartupData.inc"))
open(dst, "w", newline="\r\n").write("\n".join(out) + "\n")
changed = sum(1 for i in range(BEGIN - B, END - B) if a[i] != file_data[i])
print("%d bytes changed by the start-up code in [0x%X, 0x%X), %d runs with %d bytes written to %s" % (changed, BEGIN, END, len(runs), len(blob), dst))
